### PR TITLE
ctfd-portable-challenges-plugin updated to latest version

### PR DESCRIPTION
**Pull request by cpeter**
Updated ctfd-portable-challenges-plugin to latest version and also renamed to reflect the official name.

### CODE REVIEW

**Comment by ColdHeat** [comment]
Might be worth pointing out that the new [ctfcli](https://github.com/CTFd/ctfcli) project supports a similar feature.

**Comment by cpeter** [comment]
> Might be worth pointing out that the new [ctfcli](https://github.com/CTFd/ctfcli) project supports a similar feature.

I have looked at that project and if felt too complicated to be used. I have one git repo with a bunch of challenges, I do not want to break them apart and add them individually. 
ctfd-portable-challenges-plugin felt much simpler to use. 

The advantage of ctfcli is that there is no need to install the plugin. A combination of ctfcli and the simplicity of ctfd-portable-challenges-plugin would be the best outcome.

**Comment by ColdHeat** [comment]
You wouldn't need to break them apart, but you would have to register all of the directories to the internal `.ctf/config` file.

**Comment by ColdHeat** [comment]
I think the issue here is that ctfcli doesn't have a way to export from CTFd. Also the README is a little involved for what it does.

**Pull request merged**
